spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: dhandesaurabh2002@gmail.com
    password: lddb txuf ktun reau
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
